name: ci

on:
  push:
    branches:
      - "**"

# concurrency:
#   group: branch-${{ github.ref }}
#   cancel-in-progress: true

# env:
#   GITHUB_SHA: ${{ github.sha }}

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2